In [1]:
import numpy as np
import math
from datascience import *
from scipy import stats

Multiple Correspondence Analysis (MCA)?

So far no look into Asian Countries' specific/particular cultural/social status in Gender Equality.

## 1. Overview:

Gender equity is an essential and widely recognized international policy goal because of its intrinsic and instrumental value. It is clearly important as an end in itself and also is a means to the attainment of other development goals such as the nourishment and educational achievements of children.

The global Gender Inequality Index (GII) — built on the same framework as the Human Development Index (HDI) and the Inequality-adjusted Human Development Index (IHDI) — was released in 2010. It measures inequalities in achievements between women and men across three dimensions of human development: reproductive health, empowerment and the labour market. The GII can be used for international comparisons (the global GII), as presented in the 2010 Human Development Report (HDR). Like the HDI, the global GII’s chosen indicators are deeply affected by data limitations, but more accurate national GIIs can be developed using richer data sources. 

As we move along, we'll see how the global GII provides insights into gender disparities in reproductive health, empowerment and the labour market in 188 countries. It can enable governments and others better understand and promote gender equality. The GII can be used to raise awareness of disparities, track progress towards gender equity and support public action. 

## 2. Components:
The global GII has three dimensions: reproductive health, empowerment and labour market participation. 

a) The reproductive health dimension is measured by two indicators: the maternal mortality ratio and the adolescent fertility rate. 
b) The empowerment dimension is also measured by two indicators: the share of parliamentary seats held by each sex, and secondary and higher education attainment levels. 
c) The labour dimension is measured by women’s labour force participation rate.

Overall, there are 5 indicators belonging to 3 dimensions. Below lists the dimensions and indicators of the global GII.  

In [7]:
#Simply run this cell to show the table

Table1 = Table().with_column(
        "Dimension", ("Women's Reproductive Health", "Empowerment", "Labour Market Participation"),
        "Indicator", ("Maternal mortality ratio (MMR)", "Share of parliamentary seats held by each sex (PR)", "Labour market participation rate (LFPR)"),
        "Indicator 2", ("Adolescent fertility rate (AFR)", "Attainment at secondary and higher education (SE)", ""))
Table1

Dimension                   | Indicator                                          | Indicator 2
Women's Reproductive Health | Maternal mortality ratio (MMR)                     | Adolescent fertility rate (AFR)
Empowerment                 | Share of parliamentary seats held by each sex (PR) | Attainment at secondary and higher education (SE)
Labour Market Participation | Labour market participation rate (LFPR)            |

### 2.1 Women’s reproductive health:
The reproductive health dimension is measured by two indicators: the maternal mortality ratio and the adolescent fertility rate. These indicators are used because the degree to which a society prioritizes the well-being of women during childbirth is intrinsically important, and is also a clear signal of women’s status in society. In many countries around the world, the risk of death in childbirth could be significantly reduced through the provision of basic education, contraceptives, antenatal health services and skilled birth attendance. Adolescent childbearing tends to prevent young women from achieving higher levels of education, which is necessary for success in the labour market and accessing other life opportunities. Early childbirth also poses significant health risks for the mother and her baby. Some studies suggest that because their bodies are not yet fully developed, teenage mothers’ risk of death in childbirth is five times higher.

### 2.2 Empowerment:
The empowerment dimension is also measured by two indicators: the share of parliamentary seats held by each sex, and the percentages of men and women who are 25 years and above and have secondary or higher levels of educational attainment. Women have traditionally been disadvantaged in the political arena at all levels of government. Estimates for parliamentary representation at the national level reflect women’s visibility in political leadership and society more generally, and the extent to which women hold high offices. In turn, higher levels of educational attainment expand women’s freedoms by strengthening their capacity to question, reflect and act, and also to access information. Educated women are more likely to enjoy meaningful work, to use their voices in public debate, to be able to care for their own health and that of their family, and to act as agents throughout society. We use secondary and higher educational attainment because disparities in these levels strongly affect women’s career and leadership prospects. 

### 2.3 Labour market participation:
The labour dimension is measured by the labour force participation rate of women and men. Women may not participate in the labour market for several reasons, including exclusion, unequal pay and incentives, household duties or caring for relatives, and pregnancy and childcare. Thus, the level of women’s participation reflects several aspects, including possibilities and permission to work, which in turn includes labour market opportunities, and the capability of women to combine productive work with duties of care and reproductive responsibilities. Clearly this is affected also by men’s complementary activities in the household. 

### 2.4 Data sources:
The GII relies on data from the following publicly available databases:

• Maternal mortality ratio (MMR): UN Maternal Mortality Estimation Group (2016) [used to from UNICEF’s The State of the World’s Children]

• Adolescent birth rate (ABR): UN Department of Economic and Social Affair’s World Population Prospects (UNDESA)

• Share of parliamentary seats held by each sex (PR): International Parliamentary Union (IPU)

• Attainment at secondary and higher education levels (SE): UNESCO Institute for Statistics (2016) 
[Educational attainment statistics from Barro and Lee (2010) datasets]

• Labour market participation rate (LFPR): International Labour Organization’s LABORSTA database (ILO)

Data from the above sources, compiled by country, can be accessed through the International Human Development Indicators website at: http://HDR.undp.org/en/data/profiles/.

## 3. MEASUREMENT:

### 3.1 The geometric mean and GII
### 3.2 Computing the GII: Step-by-Step

Q: Why 10/MMR not 1/MMR?

### 3.3 Example
In this section, We'll calculate the GII for two sample countries. Let's say they are "Republic of Bears" and "The United Stanfords". The achievements of men and women of these two countries are summarized in the table below. 

In [25]:
#Simply RUN this cell to show the table 

Republic_of_Bears = Table().with_column(
    "Gender",("Female", "Male"),"MMR",(210, "-"),"ABR",(82.8, "-"),"PR",(0.25, 0.75),"SE",(0.442, 0.458),"LFPR",(0.481, 0.792))

The_United_Stanfords = Table().with_column(
        "Gender",("Female", "Male"),"MMR",(150, "-"),"ABR",(108.7, "-"),"PR",(0.171, 0.829),"SE",(0.497, 0.418),"LFPR",(0.546, 0.836))

In [26]:
Republic_of_Bears

Gender | MMR  | ABR  | PR   | SE    | LFPR
Female | 210  | 82.8 | 0.25 | 0.442 | 0.481
Male   | -    | -    | 0.75 | 0.458 | 0.792

In [27]:
The_United_Stanfords

Gender | MMR  | ABR   | PR    | SE    | LFPR
Female | 150  | 108.7 | 0.171 | 0.497 | 0.546
Male   | -    | -     | 0.829 | 0.418 | 0.836

First, we calculate the three dimension indices:

1.The **reproductive health index** of women for both countries:

Republic of Bears’ reproductive health index: (10/MMR × 1/ABR)^(1/2) = (10/210 × 1/82.8)^(1/2) = 0.0240

The United Stanfords’ reproductive health index: (10/150 × 1/108.7)^(1/2) = 0.0248

2.Then the **empowerment index** of women for both countries:

Republic of Bears’ empowerment index: (0.25×0.442)^(1/2) = 0.332

The United Stanfords’ empowerment index: (0.171×0.497)^(1/2) = 0.292


3.Finally, the **labour market participation index** of women for both countries: 

Republic of Bears’ labour market participation index: 0.481

The United Stanfords’ labour market participation index: 0.546

Next, we need to perform the same calculations for men in both countries. The empowerment and labour market participation indices are calculated in the same way for men and women. In the reproductive health dimension, men are attributed a score equal to one.

Then, we need to aggregate the achievements by geometric mean to obtain the overall achievement for each gender. For females and males we use the formulations below: 

In [43]:
*link to pics of formulation*

SyntaxError: invalid syntax (<ipython-input-43-6e6734631cb9>, line 1)

For **Republic of Bears**, we now have:

Famale: (0.0240 × 0.332 × 0.481) ^ (1/3) = 0.156
    
Male: (1 × (0.75×0.458)^(1/2) ×  0.792) ^ (1/3) = 0.774

For **The United Stanfords**, we now have:

Famale: (0.0248 × 0.292 × 0.546) ^ (1/3) = 0.158
    
Male: (1 × (0.829×0.418)^(1/2) ×  0.836) ^ (1/3) = 0.790

# NOT FINISHED

Next, we aggregate across gender groups, using a harmonic mean

Now, we calculate the geometric mean of the arithmetic means for each indicator

We then calculate the geometric mean of arithmetic mean

Finally, we calculate the GII

## 3.4 Interpreting GII results

The GII is designed to capture the inequality in achievements across genders using three important dimensions of human development. It is assumed that, for a country, the maximum ideal human development is achieved for a given set of achievements whenever they are equally distributed across genders. The GII of a country is interpreted therefore as the loss in human development due to the unequal distribution in the GII achievements between men and women as a percentage of the maximum ideal human development. This interpretation of the GII is analogous to the interpretation of the IHDI. However, note that since the GII is based on three different dimensions than those used for the HDI, it cannot be interpreted as the loss in HDI due to gender inequality.

## N. Limitations of the Global GII

The GII’s use of reproductive health indicators has been quentioned. Naturally, data for the two indicators are only available for women, making interpretations of the GII problematic. The GII responds to this discrepancy by giving men a value of “one” in this dimension—a value which signifies that men have achieved the best possible outcome here. However, a measure of inequality must consist of measurable achievements for all the groups involved. The two indicators—maternal mortality ratio and adolescent fertility rate—should instead, it is said, be used to construct an index that compares the state of women across countries, rather than a gender inequality index, comparing the situation between women and men. 

Additionally, the value of the GII doesn’t tell us which gender is doing better or worse. Instead the GII score tells us the level of inequality between two groups—men and women—but not which group is disadvantaged.

Meanwhile, several other gender indices are used by different world institutions, such as the World Economic Forum’s Global Gender Gap Index (GGI), the Economist Intelligence Unit’s Women’s Economic Opportunity Index (WEOI), the OECD’s Social Institutions and Gender Index (SIGI), and the Gender Equity Index (GEI) developed by Social Watch. They differ from the GII in many ways yet can be useful complements as we seek to understand the underlying causes of gender inequalities in economic participation. 